name: build

on:
  push:
    branches: ["main"]

  pull_request:
  workflow_call:
    outputs:
      windows:
        description: "Windows binaries"
        value: ${{jobs.build_windows.outputs.artifact}}
      linux:
        description: "Linux and MacOS binaries"
        value: ${{jobs.build.outputs.artifact}}
jobs:
  build:
    name: darwin and linux
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{steps.upload.outputs.artifact-url}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          bazel build //:for_all_platforms
          mv bazel-out/darwin_arm64-opt/bin/external/zstd\~/tar/zstd zstd_darwin_arm64
          mv bazel-out/darwin_amd64-opt/bin/external/zstd\~/tar/zstd zstd_darwin_amd64
          mv bazel-out/linux_arm64_musl-opt/bin/external/zstd\~/tar/zstd zstd_linux_arm64
          mv bazel-bin/external/zstd\~/programs/zstd zstd_linux_amd64
      - name: smoke test
        run: ./zstd_linux_amd64 --help
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: linux
          retention-days: 1
          path: |
            zstd_darwin_arm64
            zstd_darwin_amd64
            zstd_linux_arm64
            zstd_linux_amd64
  build_windows:
    name: windows
    runs-on: windows-2019
    outputs:
      artifact: ${{steps.upload.outputs.artifact-url}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          bazel build @zstd//programs:zstd
          mv bazel-bin/external/zstd~/programs/zstd.exe zstd_windows_x86_64.exe
      - name: smoke test
        run: ./zstd_windows_x86_64.exe --help
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: windows
          retention-days: 1
          path: zstd_windows_x86_64.exe